UE-108091 //UE5/Release-5.0-EarlyAccess - Compile UnrealGame HoloLens - GenericPlatformProcess.h(718): error C3861: '__rdtsc': identifier not found UE-107675 HoloLens 2 fails to package for UE5 due to 'undeclared identifiers' -Fixed arm64 hololens build break in ReadCycleCounter(), implemented it for arm & arm64. -Fixed a logic error in the case where the counter fetch always returns zero (possible on certain cpus). #jira UE-107675 #review-15319740 #rb Arne.Schober
[CL 15360086 by Jeff Fisher in ue5-early-access branch]