Lens Calibration. [Fix] Non unity build Using the raw pointer instead of static initialization of Abstract static class
error: variable type 'FBaseLensTable' is an abstract class,
https://horde.devtools.epicgames.com/job/60d22afc78c3b000011b8c2b?step=9969&issue=81489


#rb Simon Therriault
#jira none
#lockdown simon.tourangeau

#ROBOMERGE-SOURCE: CL 16755907 in //UE4/Release-4.27/...
#ROBOMERGE-BOT: RELEASE (Release-4.27 -> Release-4.27-Chaos) (v835-16672529)

[CL 16755914 by denys dubinin in 4.27-Chaos branch]